---
layout: default + 
title: "221"
---


[#question]
== 221-6445678a7b8d73457c9d3aae.

****

[#query]
--
The Scrum Master becomes aware of a list of a dozen impediments hampering the progress of the Development Team. Which of the following actions would be appropriate for the Scrum Master to do first?
--

[#list]
--
* [ ] Send the list of impediments to management and ask them to remove them immediately
* [*] Discuss the impediments with the development team and have them prioritize them
* [ ] Discuss Scrum Values with the team and explain why the team should have come to you before the list of impediments grew so large
* [ ] Inform the Product Owner and work with the Product Owner to remove the impediments

--
****

[#answer]
B

[#explanation]
--
When presented with a list of impediments, a Scrum Master should work with the team to prioritize them and then work to have the impediments that can't be resolved by the development team removed.The development team should not be allowing impediments to grow. Impediments should be brought up in the Daily Scrum as soon as they appear. But coaching the team on how to run the Daily Scrum is secondary to dealing with the issue.
--

[#ka]
Facilitation

'''

