---
layout: default + 
title: "222"
---


[#question]
== 222-6445678a7b8d73457c9d3aa7.

****

[#query]
--
The developers have a difficult, 4-week long sprint ahead of the and would like to spend Saturday and Sunday planning it. How should a Scrum Master respond?
--

[#list]
--
* [ ] The Scrum Master should inform the team that Scrum processes promote sustainable development, so they should not be working weekend planning.
* [ ] The Scrum Master should verify with HR that weekend hours will be paid for the extra work performed.
* [ ] The Scrum Masters should encourage the self-organized team of developers to do the sprint planning in whatever way they see fit.
* [*] The Scrum Master should inform the team that a one month Sprint should take less than  8 hours to plan, not an entire weekend.

--
****

[#answer]
D

[#explanation]
--
Planning for a 4 week sprint should not be a weekend-long affair.Planning for a 4 week sprint should be time-boxed to 8 hours.From the Scrum Guide: "Sprint Planning is timeboxed to a maximum of eight hours for a one-month Sprint. For shorter Sprints, the event is usually shorter."
--

[#ka]
Forecasting and Release Planning

'''

