---
layout: default + 
title: "514"
---


[#question]
== 514-64456797ca886e07fd8927d7.

****

[#query]
--
Which of the following is true about the Daily Scrum?
--

[#list]
--
* [*] It is timeboxed to 15 minutes
* [*] The Product Owner and Scrum Master are allowed to participate only under certain conditions
* [ ] It is timeboxed to 90 seconds per developer
* [ ] Must be attended by the Scrum Master
* [ ] Must be attended by the Product Owner

--
****

[#answer]
AB

[#explanation]
--
The Daily Scrum is for the Developers, and the Product Owner and Scrum Master are only allowed to participate if they are actively working on items in the Sprint Backlog.There is no requirement for the Scrum Master to attend, nor is there any requirement that the Product Owner attend."The Daily Scrum is a 15-minute event for the Developers of the Scrum Team. To reduce complexity, it is held at the same time and place every working day of the Sprint. If the Product Owner or Scrum Master are actively working on items in the Sprint Backlog, they participate as Developers." -The Scrum Guide, page 9
--

[#ka]
Events

'''

