---
layout: default + 
title: "526"
---


[#question]
== 526-64456796ca886e07fd8927d3.

****

[#query]
--
Product Backlog management includes:
--

[#list]
--
* [*] Explicitly communicating the Product Goal
* [*] Creating Product Backlog items
* [*] Ordering backlog items
* [ ] Adding Product Backlog items to the Sprint Backlog
* [*] Ensuring the Product Backlog is visible and understood

--
****

[#answer]
ABCE

[#explanation]
--
The Development team are the ones who choose which Product Backlog items become part of the Sprint Backlog.The rest of the options are all part of effective Product Backlog management."The Product Owner is also accountable for effective Product Backlog management, which includes:Developing and explicitly communicating the Product Goal;
Creating and clearly communicating Product Backlog items;
Ordering Product Backlog items; and,
Ensuring that the Product Backlog is transparent, visible and understood."-The Scrum Guide, Page 6
--

[#ka]
Product Backlog Management

'''

