

== Chapter 5
=== The Developers

Scrum has its roots in software development, but the stewards of the framework have worked hard to push Scrum into other domains including:

- Construction
- Manufacturing
- Engineering
- Bee Keeping

To pass the Scrum certification exam, you must shake yourself out of the mindset that Scrum is all about software development. 

A big mental transition many software developers have difficulty with is realizing that in terms of Scrum, a 'developer' isn't necessarily a 'software developer.'


[quote, 2020 Scrum Guide page 5]
____
Developers are the people in the Scrum Team that are committed to creating any aspect of a usable Increment each Sprint.
____

=== Who is a Developer?

According to Scrum, the term 'developer' refers to anyone on the team who is adding value and working towards the creation of a usable and valuable increment of work.

- In construction, a developer could be the person painting the walls
- For castaways on a desert island, a developer could be the person digging a trench for irrigation
- In beekeeping, a developer might be the person who disposes of the slumgum

As you read this section about the 'developer', it is easy to fall into the trap of thinking that Scrum is specifically talking about a 'software developer.'

They're not. And quite often, framing a scenario or exam question outside the world of Software development will help you choose the correct option.

=== Aspects v/s Accountability

The Scrum Certification exam will likely ask you one of these two questions:

- Who is accountable for creating useful Increment?
- Who is committed to creating aspects of a usable Increment?

The two questions sound very similar, and if you're unprepared, the nuance between the job of the Developers and the duties of the team might lose you a mark.

The Scrum Team as a whole is accountable for creating a useful Increment, not just the Developers.

However, it is the developers who create the various **aspects** of the usable Increment. 

Compare the quote above to the one below and notice the difference the Scrum Guide makes between the Scrum Team and the Developers when it comes to the Increment:

[quote, 2020 Scrum Guide - Scrum Team Section]
____
The entire Scrum Team is accountable for creating a valuable, useful Increment every Sprint.
____

[quote, 2020 Scrum Guide - Developer Section]
____
Developers are the people in the Scrum Team that are committed to creating any aspect of a usable Increment each Sprint.
____


=== Complicated Brevity

The whole point of Scrum is to deliver value to the stakeholders, and it is the developers who create all aspects of the Increment, which is the additive unit of value in Scrum.

Yet despite the importance of the developer to the framework, the Scrum Guide only dedicates 84 words to them.

The remaining verbiage about the Developers in Scrum outlines the tasks they are accountable for:

[quote, 2020 Scrum Guide - Developer Section]
____

The specific skills needed by the Developers are often broad and will vary with the domain of the work. 

However, the Developers are always accountable for:

- Creating a plan for the Sprint, the Sprint Backlog;
- Instilling quality by adhering to a Definition of Done;
- Adapting their plan each day toward the Sprint Goal; and,
- Holding each other accountable as professionals.
____

=== Developer Accountabilities

Let's take a look, At the accountabilities of the Developer one point at a time.

[quote, 2020 Scrum Guide - Developer Section]
____

Developers are always accountable for creating a plan for Sprint: the Sprint Backlog.
____


There are two backlogs in Scrum:

- One is the Product Backlog owned by a Product Owner. It outlines all of the work necessary to build the product.
- Second, is the Sprint backlog owned by the developers. 

The Sprint Backlog is the developer's plan of what they intend to get done during the Sprint. 

The developers own it, and nobody tells them how to manage it, not even the Scrum Master.

****
Who on the Scrum Team has the right to add new items to the Sprint Backlog?

* [ ] The Scrum Master
* [ ] The Product Owner
* [ ] The Stakeholders
* [ ] The Developers

****

The answer is D.

Only the Developers have the authority, to add or remove items from the Sprint Backlog.

In contrast, only the Product Owner can add or remove items from the *Product* Backlog.

'''

=== Instilling Quality

[quote, 2020 Scrum Guide page 5]
____

Developers are always accountable for Instilling quality by adhering to a Definition of Done.
____

Notice the connection between quality and the Definition of Done. 

Any time the Scrum Master certification asks how to enforce quality, the answer will usually get mapped to the application of the Definition of Done.

****
The gatekeeper of quality for the Scrum Framework is:

* [ ] The Scrum Master
* [ ] The Product Owner
* [ ] The Product Goal
* [ ] The Definition of Done
****

The answer is D. The Definition of Done is the quality gate all increments must pass through to become valid.

'''
=== Daily Adaptation

[quote, 2020 Scrum Guide page 5]
____
Developers are always accountable for adapting their plan each day toward the Sprint Goal.
____



It is an assumption that things will change and plans will go away during a Sprint. 

Developers are expected to constantly adapt their plans to adjust to changes. And since the developer's plan is the Sprint Backlog, that means the developers will be tinkering with, adding, deleting, and managing their Sprint Backlog constantly throughout a Sprint.

****
When are developers allowed to adapt their plan by changing the Sprint Backlog?

* [ ] Any time during the sprint
* [ ] During Sprint Planning
* [ ] During the Sprint Retrospective
* [ ] During the Daily Scrum
****

Option A is correct.

If the developers see an opportunity to adapt to new changes or information, they are encouraged to update their plans immediately. In Scrum, the Sprint Backlog is the developer's plan. The developers can update the Sprint Backlog anytime during the Sprint if they feel it is necessary.

'''

=== Interpersonal Accountability
[quote, 2020 Scrum Guide page 5]
____
Developers are always accountable for holding each other accountable as professionals.
____

You are guaranteed to get a question on the Scrum Certification exam about who holds the developers accountable for monitoring or tracking their progress. 

The answer is the developers. The developers hold themselves accountable.

****
Who holds the development team accountable for their work?

* [ ] The Scrum Master
* [ ] The Product Owner
* [ ] The Management Team
* [ ] The Development Team as a whole
****

The answer is D. The development team holds themselves accountable for their progress.

This four-item list ends the 'Developers' section in the Scrum Guide. This covers the basic responsibility as far as the Scrum Guide goes.

'''

=== What's not said about Developers

About 90% of the question on the Scrum Certification exam come directly out of the Scrum Guide. However, there are a few questions that require some additional knowledge.

Two topics you'll want to familiarize yourself with in regarding Developers are:

- The fact that adding developers sometimes slows down the team's velocity
- New developers can be added any time you need them.

=== Adding New Developers

When should you add new developers to a Team?

- During Sprint Planning?
- During the Sprint Review?
- During the Sprint Retrospective?

The Scrum Guide doesn't say anything decisive about this subject, but it also doesn't need to.

You can add new developers to a project any time you need them.

If you're halfway through a Sprint, and the HR team has just hired four new programmers that you've wanted for months, it wouldn't make sense to just keep those developers on the bench for two weeks so they can start at the beginning of the next Sprint. Start them right away!

So you can add new developers to the team any time they become available.

==== Sustainable Development

And when should you add developers? Scrum says developers should always work at a sustainable pace. So any time the pace starts to become unsustainable, add some new developers to the team.

The Scrum Certification exam might talk about budget money or internships or something like that, but those factors don't have anything to do with Scrum. 

In terms of Scrum, developers can be added to a project any time they are needed. They can be removed at any time too.

=== The Impact of Adding Developers

One reality of adding new developers to a team is that it tends to slow the rest of the team down.

When new developers are onboarded, they usually take other developers away from their work, as they are given help setting up printers, finding out where the washrooms are, learning about the project, and figuring out how to connect to GitHub and kick off a continuous integration build.

That's just the reality of adding new people to the team. For the short term, the productivity of individual members of the team will dip, although, over time, it will go back to normal.

Just be aware of that fact on the Scrum Certification exam.









