
== Chapter 6
=== The Product Owner

It all starts with the Product Owner (PO).

Seriously, the whole idea of Scrum is for a team to work towards the creation of a product that makes stakeholders and customers happy. 

- Who knows what the product's supposed to do?
- Who knows what features the product needs?
- Who has the product vision? 
- Who knows what features matter the most?
- Who can quickly answer questions about the product?
- Who do the stakeholders trust to make decisions about the product?

The answers to all of those questions is 'The Product Owner.'

Without a Product to build, there's no point in putting together a Scrum Team. 

=== Product Owners Maximize Value



The Product Owner knows everything there is to know about the product the team's trying to build.

[quote, 2020 Scrum Guide page 5]
____

The Product Owner is accountable for maximizing the value of the product resulting from the work of the Scrum Team. How this is done may vary widely across organizations, Scrum Teams, and individuals.
____

The Product Owner knows all about the Product. But what is the Product Owner most accountable for? 

The Scrum Guide makes the Product Owner's job clear: to maximuze the value of the product being created. 

Interestingly, the Scrum Guide doesn't make it clear as to how the Product Owner goes about doing that. Fortunately, I can help you out here.

The PO maximizes the value of the work done by the Scrum Team by making sure the developers are working on the most important and most valuable features of the product.

- If the PO gets the developers to work on a bunch of features nobody is going to use, the PO is not maximizing value. 

- If the PO gets the developers to create features the clients are dying to get their hands on, they the PO is maximizing value. 

That's typically how the PO maximizes the value of the stuff the developers are creating. 

=== Product Backlog Management

What we are essentailly describing here with regards to prioritizing the most important features is one of the four key elements of Product Backlog management. The  Scrum Guide describes Product Backlog management in more detail here:

[quote, 2020 Scrum Guide page 6]
____
The Product Owner is also accountable for effective Product Backlog management, which includes:

- Developing and explicitly communicating the Product Goal;
- Creating and clearly communicating Product Backlog items;
- Ordering Product Backlog items; and,
- Ensuring that the Product Backlog is transparent, visible and understood.
____

Take these four points seriously, because Product Backlog Management is one of the 13 categories in which the questions on the Scrum Certification exam are categorized.

The exam will try to catch you off guard with false statements that seem to make sense.

For example, the exam will assert in a True or False question that the stakeholders or customers are responsible for communicating the Product Goal. On the surface that almost sounds like it makes sense. 

After all, the product is for the customers, right? So shouldn't they communicate the Product Goal? Don't fall for the tricker. The Product Owner communicates the Product Goal.

The same tricker goes for communicating Product Backlog items (PBIs). It sounds logical that a customer or stakeholder might be the one creating or communicating Product Backlog items, after all, the Product Backlog items represents features and functionality that the customers want, right?

Again, don't fall for it. It's the Product Owner's job to create and clearly communicate Product Backlog items.

When it comes to the Product Backlog and the Product Goal, the responsibility falls on the shoulder of the Product Owner, nobody else.


==== Test Yourself

****
Who is responsible for managing the Product Backlog and maximizing the value of of the product produced?

* [ ] The Scrum Master
* [ ] The Product Owner
* [ ] The Management Team
* [ ] The Development Team as a whole
****

As we just learned, the Product Owner manages the Product backlog, and it's also the Product Owner's job to 'maximize the value of the product resulting from the work of the Scrum Team.'

'''

==== Test Yourself

****
Which of the following statements are true?

* [ ] The Scrum Master can add items to both the Sprint Backlog and the Product Backlog
* [ ] The Product Owner can add items to both the Sprint Backlog and the Product Backlog
* [ ] The Product Owner is fully accountable for all items added to the Product Backlog
* [ ] The Scrum Master is fully accountable for all items added to the Sprint Backlog
****

Only Option C is correct.

The developers have full control over the *Sprint* Backlog and they are the only ones who can add to it.

The Product Owner has full control over the *Product* Backlog and only the PO can add items to it.

Notice in the question above the term 'accountable' was used.

The Product Owner can actually delegate any of the work they are accountable to anyone they deem fit. However, the Product Owner remains fully accountable for the results, regardless of who does the work.

'''

=== Who Does the Work?

In Scrum, the developers do the developing.

In Scrum, the Scrum Master does the Scrum Mastering.

But according to the Scrum Guide, the Product Owner can get someone else to do the 'Product Owner gruntwork' for them, just so long as they remain responsible and accountable for the final results.

[quote, 2020 Scrum Guide page 6]

____
The Product Owner may do the Product Backlog management work, or they may delegate the responsibility to others. 

Regardless, the Product Owner remains accountable.
____

=== Product Ownership and Trust


Perhaps the most important quality of the Product Owner is that they have the complete and total trust of the organization to make decisions about what's best for the Product being built.

[quote, 2020 Scrum Guide page 6]
____
For Product Owners to succeed, the entire organization must respect their decisions. 
____

The importance of PO trust can't be understanted.

- Scrum teams move quickly
- Conditions change from day to day
- Adaptation should happen daily
- Backlog item clarity is of utmost importance


When the developers have questions about the work they are doing, they need answers that are clear and difinitive. 

The Product Owner must be able to respond quickly, and the development team needs to know that the decisions of the Product Owner will not be second guessed by management. 

If someone else in the organization keeps overriding the decisions of the PO, the team will quickly lose trust in the Product Owner, and the whole Scrum Framework falls apart.

==== Test Yourself

****
Important decisions that pertaining to the future direction of the product being built must be made by:

* [ ] The Scrum Master
* [ ] The Product Owner
* [ ] The Product Owner along with a stakeholder committee
* [ ] The Scrum Team as a whole
****

The answer to this question is the Product Owner.

In fact, the Scrum Guide states quite emphatically that the product based decisions are not to be made by a committe. 

'''

=== A Single Product Owner

The job of the product owner cannot be shared amongst multiple individuals. There can't be two co-Product Owners on a team.

As the Scrum Guide stated earlier, the Product Owner can delegate some of Product Backlog management work to a cohort, but in the end, all of the accountabilities associated with being a Product Owner will fall on the shoulders of only one person.

[quote, 2020 Scrum Guide page 6]
____
The Product Owner is one person, not a committee. 

The Product Owner may represent the needs of many stakeholders in the Product Backlog.
____

Notice how the Scrum Guide states that the Product Owner may represent the needs of many stakeholders. Implied in that statement is that different stakeholders might have different interests with regards to which features or enhancements should be prioritized.

When it comes to competing interests, the Product Owner is responsible for managing the expectations of the stakeholders.

==== Test Yourself

****
There are many stakeholders groups with many competing interests, including the priority of features, the cost of the project, the release date and community outreach. How should Scrum ensure the interests of each of these groups is recognized and respected?

* [ ] Have the Scrum Master represent the interests of each of these groups
* [ ] Have multiple Scrum Masters, with each Product Owner assigned to each stakeholder group
* [ ] Have one Product Owner represent the interestes of each of these groups
* [ ] Have multiple Product Owners, with each Product Owner assigned to each stakeholder group
****

There is only one Product Owner on a Scrum Team, and that one Product Owner represents the interests of all of the stakeholders.

'''




=== Keeping Tabs on the Product Owner

Stakeholders will always be interested in how the product is progressing. They will constantly want to know what's been created, and what the team will be working on next. 

The Product Backlog and inspectable Increments are how stakeholders get the answers to these question.

[quote, 2020 Scrum Guide page 6]
____
These decisions are visible in two ways:

1. through the content and ordering of the Product Backlog
2. through the inspectable Increment at the Sprint Review

Those wanting to change the Product Backlog can do so by trying to convince the Product Owner.
____



=== Trust, Transparency and the Prouduct Backlog

The PO will have the complete and total trust of the organization with regards to product ownership. But trust is a two-way street. 

If the Product Owner is to be trusted, the Product Owner must also be transparent about what they're doing.

So how does the Product Owner make their decisions transparent?

They do so by making the product backlog visible and available to all stakeholders.

- Want to know what the Product Owner is building? Look at the Product Backlog.
- Want to know what the Product Owner has prioritized? Look at the Product Backlog.
- Want to know what the Product Owner wants to build next? Look at the Product Backlog.
- Want to know how features are described? Look at the Product Backlog.
- Want to know the vision and goal for the product? Look at the Product Goal which is part of the Product Backlog.

=== Inspection of the Increment

Furthermore, at the end of every Sprint, a Sprint Review takes place where stakeholders inspect what's been done. That's known as the Increment, which represents an valuable and usable piece of the product puzzle.

If a stakeholder wants to know what's being done, they look at the Product Backlog. 

If a stakeholder wants to know what's been done, they attend the Sprint Review and inspect the increment of work that's been produced in the Sprint.

The Product Owner's commitment to visibility and transparency with regards to these things is what makes it all work.

=== Negotiating Product Features

Not everyone will agree with what should be built next, what features should be prioritized, or how product development should be managed.

- Stakeholders might disagree. 
- The Scrum Master might disagree. 
- The Developers might disagree. 

Disagreement is expected, especially in a fast moving environment where things change quickly.

If anyone wants to change the Product Backlog, update the Product Backlog, delete something from the Product Backlog or add something to the Product Backlog, they go through the Product Owner.

When it comes to the Product, and the Product Backlog that describes what's being built, the Product Owner has full control.

****
How does ensure their decisions are transparent and open?

* [ ] By making their decisions visible in the Product Backlog
* [ ] By allowing stakeholders to see how the Product Backlog has been ordered and prioritized
* [ ] By sending regular status updates to stakeholders.
* [ ] By scheduling weekly meetings between the Scrum Developers and Stakeholders
* [ ] By having the stakeholders inspect a usable Increment of work at the Sprint Review

****

In this case, options A, B and E are correct.

Remember that in Scrum we always shun 'more meetings.' The whole point of the various Scrum events, namely the Sprint Review, Sprint Retrospective and the Daily Scrum is to remove the need to schedule other, time-wasting meetings.


'''

==== Test Yourself

****

The CEO has told you, the Scrum Master, that if a key feature isn't added to the product sometime within the three months, the project will be cancelled. What action should the Scrum Master take?

* [ ] Add the feature as a Sprint Backlog item so developers can start working on it immediately
* [ ] Add a new item to the Product Backlog to represent the feature
* [ ] Cancel the Sprint and have the developers shift their focus onto this new feature
* [ ] Inform the Product Owner and facilitate a conversation between the Product Owner and the CEO

****

If a change needs to be made to the backlog, it's the Product Owner who does it. If the CEO needs a feature prioritized, the CEO has to go through the Product Owner. Nobody else has the right to do it.

'''