:pdf-theme: some-theme.yml

== Chapter 11
=== The Daily Scrum

Some frameworks and methodologies have a Daily Standup.

We don't have Daily Standups in Scrum.

First of all, the term is ableist, as not everyone can stand. 

Secondly, the idea behind a 'Daily _Standup_' is that it won't last long because people will eventually get tired of standing.

Scrum practitioners don't believe the infliction of pain is the proper way to motivate people.

[quote, 2020 Scrum Guide page 9]
____
The Daily Scrum is a 15-minute event for the Developers of the Scrum Team.

The purpose of the Daily Scrum is to inspect progress toward the Sprint Goal and adapt the Sprint Backlog as necessary, adjusting the upcoming planned work.
____

=== Adapting to Change

Things change from day to day, and changes can mess up your plans.

That's why developers get together everyday for a Daily Scrum so they can talk about anything that is impeding or accelerating their progress towards the Sprint Goal.

If things are going sideways, the developers adapt. If things are going better than expected, the developers adapt.

The goal of the Daily Scrum is for developers to talk, discuss progress, and quickly solve any problems that have arisen since they last spoke.

The Daily Scrum is time-boxed to 15 minutes. 

=== Keep the Time and Location Consistent

[quote, 2020 Scrum Guide page 9]
____
To reduce complexity, it is held at the same time and place every working day of the Sprint.
____


All Scrum events are supposed to be held at the same time and in the same location. This applies to the Daily Scrum as well.


=== The Daily Scrum is for the Developers

Let's get real about the Daily Scrum for a minute.




==== Test Yourself

****
Which of the following is the responsibility of the Scrum Master regarding the Daily Scrum?

* [ ] The Scrum Master should coach the developers about keeping the Daily Scrum timeboxed to 15 minutes
* [ ] The Scrum Master should ensure each developer gets a chance to speak
* [ ] The Scrum Master starts the Daily Scrum by asking the 3 standard Daily Scrum questions
* [ ] The Scrum Master starts the Daily Scrum by asking every developer to stand up.

****

The only correct option here is A.

The Daily Scrum is for the developers. It is run by developers and managed by developers.

The only role the Scrum Master in the Daily Scrum is ensuring it is run in such a way that complies with the rules of Scrum. With regards to this quiz question, that means the only correct option is keeping the Daily Scrum to less than 15 minutes.

Past Scrum Guides mentioned the 3 Daily Scrum questions:

- What did you do yesterday?
- What do you plan to do today?
- Is anything impeding your progress?

These questions were removed from the 2020 Scrum Guide. 

They can be asked if the developers find them helpful, but they are certainly not a requirement of the Daily Scrum.

'''



==== Test Yourself

****
The development team has decided to only work one day a week and will only hold the Daily Scrum on Mondays. How do you react as a Scrum Master?

* [ ] Inform the team Scrum development cannot happen only one day a week
* [ ] Have Human Resources talk to the development lead about their proposed work schedule
* [ ] Cancel the Sprint and consult the Product Owner
* [ ] Inform the team this is fine so long as the work takes place on Monday

****

There's nothing in the Scrum Guide that forbids a team from working once a week.

The only requirement is that the Daily Scrum happens every workday. So if the one day a week the team works is Monday, then the Daily Scrum should take place on a Monday.

'''

==== Test Yourself

****
The Scrum team wants to move the Daily Scrum to the atrium on Fridays to help them wind down after a busy workweek. How do you, as a Scrum Master, respond?

* [ ] Explain to them that the Daily Scrum must take place at the same time and place
* [ ] Allow the developers to be self-managed and hold their Daily Scrum in the Atrium on Fridays
* [ ] Confirm with the Product Owner that it is okay to change the Daily Scrum location on Fridays
* [ ] As the Scrum Master, work to remove any impediments standing in the way of running the Friday Scrum in the atrium

****

Option A is correct.

The Scrum Guide says the Daily Scrum must take place, each workday, at the same time and place. 

'''

=== When Scrum Masters and POs do Development

Have you ever seen a Scrum Master or Product Owner do some work that becomes part of a usable Increment? If they do, they become developers themselves.

[quote, 2020 Scrum Guide page 9]
____
If the Product Owner or Scrum Master is actively working on items in the Sprint Backlog, they participate as Developers.
____

This is an interesting statement that answers several questions about how Scrum works.

People often wonder if a Scrum Master or Product Owner is allowed to actively do development. Of course, they can!

If a Scrum Team of five people is cast away on a desert island and scrambling to build a shelter before a storm comes, everyone on that Scrum Team going to pitch in. If your life is on the line, you're not going to refuse to help build a shelter just because you've accepted the designation of Scrum Master.

On small teams and startups, the Scrum Master might also be the Product Owner and they might be a developer as well. It might not be a best practice, but there's nothing that forbids it. And more to the point, it might make a lot of sense in a really small development firm.

So yes, a developer can also be a Scrum Master or a Product Owner or vice versa.

The only requirement is that if a Scrum Master or Product Owner does development, they are expected to attend the Daily Scrum and participate as though they were a developer, not the Scrum Master or PO. They relinquish their Scrum Master or Product Owner accountabilities while the Daily Scrum takes place.

=== Who participates in the Daily Scrum?

[quote, 2020 Scrum Guide page 9]
____
The Developers can select whatever structure and techniques they want, as long as their Daily Scrum focuses on progress toward the Sprint Goal and produces an actionable plan for the next day of work. 
This creates focus and improves self-management.
____

The Daily Scrum is for the developers. It should be run by the developers, organized by developers, and managed by the developers. How they manage or organize it is up to them.

Anyone can attend the daily Scrum. If the developers want to hire a circus clown to create balloon animals while the Daily Scrum proceeds, then all the power to them. But only the developers are supposed to participate.

Now that's not to say the developers can't ask the Scrum Master or Product Owner a question during the Daily Scrum. That may be necessary to properly adapt their plan towards the sprint goal. But the Scrum Master, Product Owners, and stakeholders shouldn't be active participants driving the meeting. The meeting should be driven by the developers.

=== Purpose of the Daily Scrum

[quote, 2020 Scrum Guide page 9]
____
Daily Scrums improve communications, identify impediments, promote quick decision-making, and consequently eliminate the need for other meetings.
____

Things change from day to day. The Daily Scrum is a time for developers to deal with issues that have arisen that may delay their progress and put the Sprint Goal in jeopardy.

Hopefully having the whole team of developers together in Scrum will help to bring about quick solutions to problems the team might face.

Also, note that the goal of the Daily Scrum is to reduce the need for other meetings.

One complaint I often hear about Scrum is that there are too many meetings. That shouldn't be the case. The Daily Scrum should eliminate the need for other meetings.

=== Meetings Don't Replace Pragmatic Communication

[quote, 2020 Scrum Guide page 9]
____
The Daily Scrum is not the only time Developers are allowed to adjust their plans. 
They often meet throughout the day for more detailed discussions about adapting or re-planning the rest of Sprint’s work.
____

Don't ever think that the Daily Scrum is the only time developers are allowed to talk about their work, or that it's the only time to change the Sprint plan.

If a team of construction workers was putting up a roof, and a wind gust blew all their shingles away, would they wait until the next day's Scrum to form a new plan, or would they reformulate their plans right away?

Developers can meet with each other any time they like. They can schedule additional meetings as a group. They can meet one on one at each other's desks. They can have dinner together after work.

There's nothing in the Scrum Guide that restricts communication between developers, stakeholders, product owners, scrum masters, or anyone else. The only thing the Scrum Guide provides is a few time-boxed events that guarantee opportunities for communication, transparency, and adaptation to take place.

==== Test Yourself

****
A critical bug has appeared in your code that may put the Sprint Goal at risk. What should you, as a developer, do?

* [ ] Speak to your fellow developers as soon as possible to find a way to adapt the Sprint plan
* [ ] Bring the issue up in the next day`s Daily Scrum meeting
* [ ] Inform the Scrum Master and have the Scrum Master remove the impediment
* [ ] Pass the issue to the Quality Assurance team and continue working on Product Backlog items

****

Any time an issue comes up it should be addressed as soon as possible.

If a critical bug appears in your code, and you think it will impact the Sprint Goal, then meet with your fellow developers and see if you can adapt by adjusting the Sprint plan.

Don't ever let the Scrum Guide and the various Scrum events and artifacts impede pragmatic thinking. If a problem arises that needs to be taken care of immediately, take care of it immediately. Don't wait for the next Scrum event to adapt.

'''
