
== Chapter 12
=== Sprint Review

On any project, not just in the domain of Scrum, stakeholders should continually get updates on the state of the product they're invested in having built.

That's one of the ideas behind the continuous delivery of software - to constantly deliver software to your clients and stakeholders every time a new feature or Increment of value has been completed.

The more often the stakeholders see new features added to the product, the more in tune they will be with the pace at which the project is progressing.

Of course, not every organization can continuously deliver updates daily. But at the very least, a development team should allow the stakeholders to inspect what has been completed and provide feedback so the team can adapt accordingly.

The Sprint Review exists to make sure that stakeholders get at least one chance to inspect the work completed during every Sprint, but it certainly doesn't have to be the only time stakeholder inspection takes place.

=== Review, Inspect and Adapt


[quote, 2020 Scrum Guide page 9]
____
The purpose of the Sprint Review is to inspect the outcome of the Sprint and determine future adaptations. 
The Scrum Team presents the results of their work to key stakeholders and progress toward the Product Goal is discussed.
____

The Sprint Review is the one Scrum event where everyone is invited and asked to participate. That not only includes everyone on the Scrum Team but stakeholders as well.

The purpose of the Sprint Review is pretty self-explanatory. It's for everyone to review what was done and talk about what they like, what they don't like, and where they think things should go next.

Everyone gets to speak at the Sprint Review. Developers can speak to stakeholders, stakeholders can speak to the Scrum Master, and the Product Owner can speak to developers.

Note that there is never any restriction in Scrum about developers talking to stakeholders, or the Scrum Master talking to stakeholders, or anything like that.

The Spring Review intentionally and concertedly brings everyone together, but there's no rule says developers can't talk to stakeholders about development when they pass each other in the hallways at work. The more openness and transparency the better.

==== Test Yourself

****
Which of the following is true about the Sprint Review?

* [ ] Only the Scrum Master is allowed to talk directly to stakeholders
* [ ] Only the Product Owner is allowed to talk directly to stakeholders
* [ ] Developers are not allowed to talk directly to stakeholders
* [ ] The Sprint Review is the only Scrum event where both Stakeholders and the Scrum Team are invited

****

Option D is correct.

Anyone is allowed to talk during the Sprint Review. There's no rule anywhere in Scrum that restricts developers from talking directly to stakeholders.

The Sprint Review is a planned event that brings everyone together to discuss progress, but stakeholders and members of the Scrum Team are allowed to talk directly to each other at any time during the Sprint

'''

=== What to show in the Review?

There's a small detail left out of this discussion of the Sprint Review which is somewhat important. For example, the following sentence doesn't exactly specify what the stakeholders get to see during the Sprint Review.

[quote, 2020 Scrum Guide page 9]
____
During the event, the Scrum Team and stakeholders review *what was accomplished* in the Sprint and what has changed in their environment. 
____

The term *what was accomplished* is somewhat vague.

We discover in the Scrum Guide's section on artifacts that only completed Increments, that is work items that have met the Definition of Done, are to be presented at the Spring Review.

[quote, 2020 Scrum Guide page 12]
____
Multiple Increments may be created within a Sprint. The sum of the Increments is presented at the Sprint Review thus supporting empiricism.

Work cannot be considered part of an Increment unless it meets the Definition of Done.
____

Any work that is partially done is not to be presented at the Sprint Review. Only Increments, or the sum of all the Increments created during the Sprint, are to be discussed at the Sprint Review.

=== A Discussion on What to do Next

[quote, 2020 Scrum Guide page 9]
____

Based on this information, attendees collaborate on what to do next. 

The Product Backlog may also be adjusted to meet new opportunities.
____

The Sprint Review gives everyone on the team and the stakeholders a chance to talk about what they like, what they don't like, and what they think should change in terms of how the product is being developed.

If the stakeholders think some features don't work and should be removed, the Product Owner may remove those features from the Product Backlog. If there are features the stakeholders decide they want, then the Product Owner can either add them to the Product Backlog or prioritize them if they already exist.

The Sprint Review helps create transparency, is an opportunity for inspection, and allows for adaptation.

=== Sprint Review != a Presentation

[quote, 2020 Scrum Guide page 9]
____
The Sprint Review is a working session and the Scrum Team should avoid limiting it to a presentation.
____

The Scrum Master Certification exam will likely include a question or two where one of the incorrect options implies that the purpose of the Sprint Review is to simply do a demo or deliver a presentation. Don't fall for that.

The purpose of the Sprint Review is to inspect the work that was performed during the Sprint and adapt according to feedback received from the stakeholders. At the end of a Sprint Review, the stakeholders should know what was done during the previous Sprint, and the Scrum Team should have a better idea of what they should be working on next.

[quote, 2020 Scrum Guide page 9]
____
The Sprint Review is the second to last event of the Sprint and is time-boxed to a maximum of four hours for a one-month Sprint. 

For shorter Sprints, the event is usually shorter.
____


You are guaranteed to get questions about the timebox length of every event. Remember that the Sprint Review is time-boxed to a maximum of 4 hours.


****
Which of the following Scrum events are time-boxed to 4 hours?

* [ ] The Sprint Review only
* [ ] The Sprint Retrospective only
* [ ] Sprint Planning only
* [ ] The Sprint Review and the Sprint Retrospective
* [ ] The Sprint Review and Sprint Planning

****

Both the Sprint Review is time-boxed to 4 hours. 

The Sprint Retrospective is 3 hours. 

The Sprint Planning event is capped at 8 hours, and the Daily Scrum is 15 minutes.

'''

When the Sprint Review is complete, it's time for the team to do a Sprint Retrospective, after which the Sprint comes to an end.
