:pdf-theme: some-theme.yml

== Chapter 15
=== The Product Backlog

As we learned earlier, the Product Owner is the one person on the Scrum Team who is tasked with the job of optimizing the value of the work done by the Scrum Team.

The way the Product Owner does that is by keeping a list of all of the features and facets the product under development requires.

This list is known as the Product Backlog, and by prioritizing entries in the Product Backlog and encouraging developers to work on the most important ones, stakeholders and customers get delivered the features they want and need the most.


[quote, 2020 Scrum Guide page 10]
____
The Product Backlog is an emergent, ordered list of what is needed to improve the product. 
____


This definition makes it clear that the Product Backlog is a list of the features that need to be built to complete the project.

This definition also demands that the list be ordered, in a proprity sequence. The most important items are at the top.

==== Test Yourself

****
True or False: The Product Backlog is a prioritized lists the things that are needed to improve the product.

****

This is true. This precicely describes the purpose of the Product Backlog.


=== Single Source of Work

[quote, 2020 Scrum Guide page 10]
____

The Product Backlog is the single source of work undertaken by the Scrum Team.
____

The fact that this is the single source or work to be undertaken by the Scrum Team indicates that it is also the only source of work undertaken by the Scrum team.

If the Scrum Team is going to work on something, then it has to first be part of the Product Backlog.

****
True or False: The Scrum Master can assign work to the Scrum Developers that is not a part of the Product Backlog.

****

This is false.

The Product Backlog is the only source of work for the Scrum Team.

'''


=== Product Backlog Refinement

[quote, 2020 Scrum Guide page 10]
____

Product Backlog items that can be Done by the Scrum Team within one Sprint are deemed ready for selection in a Sprint Planning event. 

They usually acquire this degree of transparency after refining activities. 

Product Backlog refinement is the act of breaking down and further defining Product Backlog items into smaller more precise items. 

This is an ongoing activity to add details, such as a description, order, and size. 

Attributes often vary with the domain of work.
____

Developers may see a high priority Product Backlog item that is far too complex to complete in a 3 or 4 week Sprint. When this happens, the developers work with the Product Owner to break the item down into something more manageable.

The goal is always to break a Product Backlog item into something that can be completed within a Sprint. And remember that druing Spritn planning, the developers are expected to break all of the selected Product Backlog items down into units of work that can be completed in a day or less.

[quote, Sprint Planning page 8]
____
For each selected Product Backlog item, the Developers plan the work necessary to create an Increment that meets the Definition of Done. 
This is often done by decomposing Product Backlog items into smaller work items of one day or less.
____


==== Test Yourself

****
When picking Product Backlog items for the current Spring, Scrum Developers must:

* [ ] Only choose Product Backlog items they believe the can complete within Sprint
* [ ] Refine large Product Backlog items down until they are large enough to complete in a Sprint
* [ ] Not be afraid to choose Product Backlog items that may span multiple Sprints
* [ ] Decompose large Product Backlog items down until they are large enough to complete in a day

****

Option B is correct.

There will often be Product Backlog items that are too large to complete in a single Sprint.

In those instances, the development team refines those large Product Backlog Items until a piece is uncovered that can be completed in the current Sprint.

'''

==== Test Yourself

****
Breaking Product Backlog items selected for the Sprint down into smaller work items of one day or less is called:

* [ ] Grooming
* [ ] Refinement
* [ ] Decomposition
* [ ] Planning

****

Option C is correct.

The Scrum Guide desribes decomposition as breaking Product Backlog items into smaller work items of one day or less.

'''

==== Test Yourself

****
Breaking large Product Backlog items down into smaller, more precise items is known as:

* [ ] Grooming
* [ ] Refinement
* [ ] Decomposition
* [ ] Planning

****

Option B is correct.

The Scrum Guide defines Product Backlog refinement as: the act of breaking down and further defining Product Backlog items into smaller more precise items.

'''

==== Test Yourself

****
When does Product Backlog refinement occur:

* [ ] Product Backlog refinement happens during Sprint Planning
* [ ] Product Backlog refinement happens during the Sprint Retrospective
* [ ] Product Backlog refinement happens during the Daily Scrum
* [ ] Product Backlog refinement ongoing activity that happens throughout the Sprint

****

Option D is correct.

The Scrum Guide has very few rules about what should happen when.

If a Product Backlog item needs more details, be refined, be decomposed or anything else, then just do it!

When work needs to be done, don't wait for an official Scrum event to do it. Just get the work done!

'''

==== Test Yourself

****
The developers are not happy with how the Sprint framework has being implemented. When is the best time to discuss this?

* [ ] During the Sprint Review
* [ ] During the Daily Scrum
* [ ] During the Sprint Planning
* [ ] During the Sprint Retrospective

****

Option D is correct.

Discussions about how things are working, how various processes are being implemented, and even discussion about how to do Scrum better should happen during the Sprint Retrospective.

'''

=== Estimation and Sizing

[quote, 2020 Scrum Guide page 10]
____

The Developers who will be doing the work are responsible for the sizing. 

The Product Owner may influence the Developers by helping them understand and select trade-offs.
____

This point keeps coming up and up again in the Scrum Guide, and you can expect it to come up again and again on the certification exam.

Only the developers know what it takes to accomplish a given piece of work. Only the developer can size up Product Backlog Items and estimate how much time a given feature will take.


==== Test Yourself

****
Who is responsible for estimating how many Product Backlog Items can be completed in a Sprint?

* [ ] The Product Owner
* [ ] The Scrum Master
* [ ] The Scrum developers
* [ ] The stakeholders

****

Option C is correct.

The developers are the experts. Only the developers know how long it will take to complete a Product Backlog item.

'''

==== Test Yourself

****
True or false: Taking into account upcoming vacation time is more empirical than estimating productivity based on burndown charts?

****

This is true.

Burndown charts and velocity calculations are great, but they are not a replacement for actualy knowledge and real-world experience.

'''


=== Commitment: Product Goal

[quote, 2020 Scrum Guide page 11]
____

The Product Goal describes a future state of the product which can serve as a target for the Scrum Team to plan against.
____

Every arrow needs a target.

As the Scrum Team works to build the product, they need to know what the product is that they're building. The Product Goal serves this purpose.


****
True or false: The Product Goal represents the current state of the project?
****

This is false.

The Product Goal represents the future state of the project.

'''

=== Product Goal and the Product Backlog

[quote, 2020 Scrum Guide page 11]
____

The Product Goal is in the Product Backlog.

The rest of the Product Backlog emerges to define "what" will fulfill the Product Goal.
____


This line, "the Product Goal is in the Product Backlog", actually confuses me.

The Product Backlog is an ordered list of what is needed to improve the product. That's what it says on page 10 of the Scrum Guide.

[quote, 2020 Product Backlog Definition page 10]
____

The Product Backlog is an emergent, ordered list of what is needed to improve the product.
____

So does this statement mean the Product Goal is one of the items in the list?


****
The Product Backlog has many items that have never been assessed and likely won't be worked on within the next year.
What should the Product Owner do to clean up the Product Backlog?

* [ ] Create a second Product Backlog and moved these items there
* [ ] Delete the old items items from the Product Backlog
* [ ] Prioritize these Product Backlog items so the developers complete them
* [ ] Leave the Product Backlog items in the Product Backlog as they are

****

Options D is correct.

The Product Backlog contains everything needed to create the product and achieve the Product Goal.

If a Product Backlog item contributes to the completion of the Product Goal, then it must be in the Product Backlog.

'''

=== Value Delivery

[quote, 2020 Product Backlog Definition page 11]
____

A product is a vehicle to deliver value. 

A product has:

- a clear boundary, 
- known stakeholders, 
- well-defined users or customers. 

A product could be a service, a physical product, or something more abstract.
____

The people behind the Scrum Guide have worked hard to get people out of the mindset that Scrum is just for software development.

This section further emphases the point that Scrum can be used to develop more than just software.

==== Test Yourself!

****
During the Sprint, the product being built has:

* [ ] An approved budget
* [ ] Known stakeholders
* [ ] Well-defined users
* [ ] Has unclear boundaries

****

Options B and C are correct.

The Scrum Guide does not say anything about the topic of budgets, so option A is correct.

Option D is incorrect because the Scrum Guide insists that the product being built has clear boundaries.

'''


=== One and Only Objective

[quote, 2020 Product Backlog Definition page 11]
____
The Product Goal is the long-term objective for the Scrum Team. 

They must fulfill (or abandon) one objective before taking on the next.
____

According to the Scrum Guide, a Scrum Team can only work on one project at a time. They can't have their efforts split between two separate projects.

It's noteworthy that that doesn't mean an individual Developer or Scrum Master can't be on multiple teams at the same time.

I've quite often seen UI designers who have only a small part to play on a set of active projects be part of multiple Scrum Teams at the same time, and it's also very common for Scrum Masters to be on three or four different teams at a time. There is no rule against an individual being on multiple teams with separate objectives, but a single Scrum Team can only have one objective in mind.

==== Test Yourself!

****
The Product Owner beleves the Scrum Team has enough capacity to work on two separate projects concurrently. How do you, as the Scrum Master, advise the Product Owner to go forward with this plan?

* [ ] Double the timebox for all Scrum events
* [ ] Create a second Product Backlog for the new project
* [ ] Add features for the new Project into the current Product Backlog
* [ ] Inform the Product Owner that a Scrum team can only work on one product at time

****

Option D is correct.

A Scrum Team must fullfill or abandone one objective before taking on the next.

'''













