:pdf-theme: some-theme.yml

== Chapter 16
=== The Sprint Backlog

[quote, 2020 Scrum Guide page 11]
____
The Sprint Backlog is composed of:

- the Sprint Goal (why)
- the set of Product Backlog items selected for the Sprint (what)
- an actionable plan for delivering the Increment (how)

The Sprint Backlog is a plan by and for the Developers.
____

The Developers on the Scrum Team completely control the Sprint Backlog.

The Product Owner cannot add to it and the Scrum Master can't delete anything from it. 

The Developers completely control the Sprint Backlog.

Contrast that against the Product Backlog which is entirely controled by the Product Owner.

What does that leave the Scrum Master to control? Very little, other than a responsibility to guide the team and organization on how to properly apply the Scrum framework.


==== Test Yourself

****
The Sprint Backlog answers which three questions?

* [ ] When, where and why
* [ ] Who, when and where
* [ ] Why, what and how
* [ ] How, what and where

****

Option C is correct.

The Sprint Backlog answers the questions why, what and how.

'''


==== Test Yourself

****
The CEO talks to you, the Scrum Master, and tells the project will be cancelled if a given feature is not implemented before the end of the Sprint.
What should you as the Scrum Master do?

* [ ] Add the feature as a Sprint Backlog item in the current Sprint
* [ ] Cancel the Sprint and have the team work on this important feature
* [ ] Have the Product Owner speak with the CEO
* [ ] Have the Product Owner add the feature to the current Sprint Backlog

****

Nobody can add anything to the Sprint Backlog other than the developers.

In this case, the Scrum Master should have the Product Owner speak to the CEO.

The Product Owner could then speak with the developers and see if they could include the new feature in the Sprint Backlog without putting the Sprint Goal at risk.

'''

[quote, 2020 Scrum Guide page 11]
____
The Sprint Backlog is a highly visible, real-time picture of the work that the Developers plan to accomplish during the Sprint in order to achieve the Sprint Goal.
Consequently, the Sprint Backlog is updated throughout the Sprint as more is learned. 
It should have enough detail that they can inspect their progress in the Daily Scrum.
____

One of the pillars of Scrum is transparency.

The Sprint Backlog helps to create transparency by allowing everyone on the Scrum Team, along with all of the stakeholders, know exactly what's going on during a Sprint.

Management shouldn't have to pester the Scrum Team with status meeting and email updates because the Sprint Backlog should answer any questions about what is being developed and how things are moving along.

==== Test Yourself

****
When should the Sprint Backlog be updated?

* [ ] During Sprint planning when more details emerge
* [ ] During the Daily Scrum as the Scrum developers adapt
* [ ] During the Sprint review as stakeholders give feedback
* [ ] During the Sprint any time more is learned

****

Option D is correct.

The Sprint Backlog should be an up-to-date reflection of what is being done and what has been done.

It should be updated regularly.

'''

=== Sprint Goal

[quote, 2020 Scrum Guide page 11]
____
The Sprint Goal is the single objective for the Sprint. 
Although the Sprint Goal is a commitment by the Developers, it provides flexibility in terms of the exact work needed to achieve it. 
The Sprint Goal also creates coherence and focus, encouraging the Scrum Team to work together rather than on separate initiatives.
____

The Sprint Goal is the commitment the Sprint Backlog makes. 

The Sprint Goal describes what the developers are trying to achieve in the current Sprint. It gives the team something to aim at.

Now let's make one thing clear - the development team doesn't always achieve the Sprint Goal, and that's okay.

In fact, some teams might not achieve the Sprint Goal the majority of the time. If that's a problem, them maybe it's something the team can talk about in the Sprint Retrospective. But at the same time, it might not actually be a problem.

What matters is that the Sprint Goal drives the team forward. So long an a usable increment of work is produced at the end of the Sprint and progress is made towards building the product, a missed goal isn't the end of the world.


==== Test Yourself

****
Issues beyond the Scrum Team's control have made almost impossible to achieve the Sprint Goal, and there's still a week left in the Sprint. What should the Scrum Master do?

* [ ] Change the Sprint Goal
* [ ] Cancel the Sprint
* [ ] Schedule a mid-Sprint planning session
* [ ] Have the team continue to work towards the goal

****

The Sprint can't be cancelled unless the Sprint Goal is obsolete, and that's rare.

And you're also not allowed to change the Sprint Goal once it's finalized.

The correct answer here is to just keep working towards the Sprint Goal. 

It's not the end of the world if the Sprint Goal is not achieved. Sprints are short. You can create a new Sprint Goal when the current Sprint is finished.

'''

[quote, 2020 Scrum Guide page 11]
____
The Sprint Goal is created during the Sprint Planning event and then added to the Sprint Backlog. 
As the Developers work during the Sprint, they keep the Sprint Goal in mind. 
If the work turns out to be different than they expected, they collaborate with the Product Owner to negotiate the scope of the Sprint Backlog within the Sprint without affecting the Sprint Goal.
____

It's not unusual for teams to overestiate how much work they can accomplish during a Sprint.

If developers need to decompose backlog items or even remove items from the Sprint Backlog, that's fine, so long as all of this happens without risking the Sprint Goal.

==== Test Yourself

****
If Developers find the scope of work scheduled for a Sprint is too much, with whom should they negotiate the Sprint Backlog's scope?

* [ ] The Product Onwer
* [ ] The Scrum Master
* [ ] Their fellow developers
* [ ] The stakeholders.

****

Any time the developers need to scale back on their work, or breakdown Product Backlog items into smaller pieces, it's always wise to speak with the Product Owner for clarification. The Product Owner can also help developers understand which product features should be included in order not to put the Sprint Goal at risk.


'''











