---
layout: default 
title: "101 - Sprint burndown charts are an efficient "
---


[.question]
== Number 101-63effa169ebbe935e4c16a8d

****

[.query]
A Sprint burndown chart can be used to show the amount of work completed versus the work estimated for a project. 

What else is true about burndown charts?

[.list]
* [ ] A. Burndown charts were mentioned in previous Scrum Guides but not the current one.
* [ ] B. The Scrum Guide discourages the use of burndown charts because they are not Agile.
* [ ] C. Burndown charts have always been recommended by the Scrum Guide as a way to gauge progress.
* [*] D. Burndown charts are useful but do not replace the importance of empiricism.
****

[.answer]
D

[.explanation]
Burn-down charts are like any other metric insomuch as they can be helpful for forecasting, but they cannot predict the future, and they should not replace the importance of empiricism.

"Various practices exist to forecast progress, like burn-downs, burn-ups, or cumulative flows. While proven useful, these do not replace the importance of empiricism. In complex environments, what will happen is unknown. Only what has already happened may be used for forward-looking decision making."****

[.ka]
ka:Empiricism

'''

