---
layout: default 
title: "114 - Which of the following best describes an"
---


[.question]
== Number 114-63effd1e9ebbe935e4c16af9

****

[.query]
According to the Scrum Guide, which of the following is true about the Increment?

[.list]
* [*] A. Each new Increment gets added to all the prior Increments
* [ ] B. An Increment doesn't have to be usable.
* [ ] C. Only one Increment can be created per Sprint.
* [*] D. An Increment must be compatible and work with all previous increments.
* [*] E. An Increment is a concrete stepping stone toward the Product Goal.
****

[.answer]
ADE

[.explanation]
An increment must be usable and and multiple increments can be created per Sprint, which makes those two options wrong.

The correct options come directly out of the Scrum Guide's definition of a Sprint:

"An Increment is a concrete stepping stone toward the Product Goal. Each Increment is additive to all prior Increments and thoroughly verified, ensuring that all Increments work together. In order to provide value, the Increment must be usable."****

[.ka]
ka:Product Value

'''

