---
layout: default 
title: "116 - Who owns the Sprint Backlog Scrum Master"
---


[.question]
== Number 116-63effb1a9ebbe935e4c16aac

****

[.query]
According to the Scrum Guide, who is the owner of the Sprint Backlog?

[.list]
* [ ] A. The Scrum Team.
* [ ] B. The Product Owner.
* [ ] C. The Scrum Master.
* [*] D. The Development Team.
****

[.answer]
D

[.explanation]
The Development Team owns the Sprint Backlog.

In Scrum, the Development Team is responsible for delivering a potentially releasable increment of the product at the end of each Sprint. The Sprint Backlog is the plan for achieving this goal, and it consists of the work items the Development Team has committed to completing during the Sprint.

The Development Team owns the Sprint Backlog because they are the ones who will be doing the work. They are the experts in the technical aspects of the project and are best positioned to determine what tasks are necessary to deliver the product increment. They have the knowledge and skills required to estimate the effort needed for each item and to determine the order in which they should be completed.

While the Product Owner is responsible for prioritizing the Product Backlog and ensuring that the product increment meets the needs of the stakeholders, they are not responsible for creating or managing the Sprint Backlog. The Product Owner may work with the Development Team to refine the items in the Product Backlog and provide guidance on priorities, but the final decision on what work to include in the Sprint Backlog ultimately lies with the Development Team.

The Scrum Master's role is to facilitate the Scrum process and help the team improve their performance. They are not involved in managing the Sprint Backlog, but they may provide support and guidance to the Development Team as needed.

In summary, the Development Team owns the Sprint Backlog because they are responsible for delivering the product increment and have the technical expertise to plan and execute the work required to achieve that goal. The Product Owner is responsible for prioritizing the Product Backlog and ensuring that the product increment meets the needs of the stakeholders, while the Scrum Master facilitates the Scrum process and helps the team improve their performance.

[.ka]
ka:Artifacts

'''

