---
layout: default 
title: "124 - What is the best suited structure for De"
---


[.question]
== Number 124-63effa6a9ebbe935e4c16a97

****

[.query]
Creating and clearly communicating Product Backlog items is an important activity within the Scrum Framework. 

Who's job it it to create clear Product Backlog items? Choose the best answer.

[.list]
* [ ] A. The Scrum Master.
* [ ] B. The Scrum Master, or someone the Scrum Master delegates to.
****

[.answer]
D

[.explanation]
According to the Scrum Guide, the Product Owner is accountable for creating Product Backlog Items, but they do not have to personally create them. They can delegate this responsibility to others.

The Product Owner is also accountable for effective Product Backlog management, which includes:
&#9679; Developing and explicitly communicating the Product Goal;
&#9679; Creating and clearly communicating Product Backlog items;
&#9679; Ordering Product Backlog items; and,
&#9679; Ensuring that the Product Backlog is transparent, visible and understood.
The Product Owner may do the above work or may delegate the responsibility to others. Regardless, the Product Owner remains accountable.

[.ka]
ka:Product Backlog Management

'''

