---
layout: default 
title: "149 - Which two are valid actions Scrum Master"
---


[.question]
== Number 149-63effec69ebbe935e4c16b2b

****

[.query]
Sprint Planning finished only two days ago, but the developers have realized they are in over their head.

They've realized there is no way they can complete the work they've selected for the Sprint Backlog.

What should you do as the Scrum Master?

[.list]
* [ ] A. Cancel the Sprint and reconvene developers for a new Sprint Planning meeting
* [*] B. Have the developers communicate their thoughts with the Product Owner, continue the Sprint, and monitor the team's progress
* [ ] C. Recruit other developers within the organization to help until the team catches up on the work
* [*] D. Change or removed selected Product Backlog items, ensuring the Sprint Goal is not effected
* [ ] E. Work overtime to get as much of the selected work done before the end of the Sprint
****

[.answer]
BD

[.explanation]
You don't cancel a Sprint once it's started.

It's not unusual to pick too much work for a Sprint. If that happens, just make sure everyone on the team is aware, and possibly remove some Sprint Backlog items. Work with the Product Owner when you do that so a change to the Sprint Backlog has the smallest impact on the delivery of value.

[.ka]
ka:Product Backlog Management

'''

