---
layout: default 
title: "157 - Which of these is the guideline that a S"
---


[.question]
== Number 157-63effd9b9ebbe935e4c16b08

****

[.query]
The Product Owner is having a difficult time estimating how long it will take to implement various Product Backlog items, and comes to the the Scrum Master for some guidelines on how best to do estimates.

What advice or guidance would you, as a Scrum Master, provide?

[.list]
* [ ] A. Try to estimate Product Backlog items in story points.
* [ ] B. Scrum frowns upon given hard estimates for completing Product Backlog Items
* [ ] C. Estimates are allowed to have a large margin of error
* [*] D. Estimates should be done by the Development Team, not the Product Owner
* [ ] E. The Product Owner has to make estimated independently from the developers or Scrum Master
****

[.answer]
D

[.explanation]
Option D is correct.

In Scrum, the people who do the work do the estimates of how long it will take to complete the work.

The developers estimate the work, not the Product Owner.****

[.ka]
ka:Product Backlog Management

'''

