---
layout: default 
title: "159 - True or False The Product Owner makes su"
---


[.question]
== Number 159-63effb099ebbe935e4c16aaa

****

[.query]
The Product Owner must ensure that the Scrum Developers add enough items to the Sprint Backlog to ensure stakeholders are satisfied with the Increment of Work delivered at the end of the Sprint.

[.list]
* [ ] A. True
* [*] B. False
****

[.answer]
B

[.explanation]
In Scrum, the Scrum Development Team is responsible for creating and managing the Sprint Backlog, which is a list of items that the team plans to deliver during the next sprint. The team is accountable for completing the work they commit to during the sprint, and they have the final say over what goes into the Sprint Backlog.

The reason for this is that the Scrum Development Team is the group of individuals who will actually be doing the work to deliver the product increment. They are the experts in their domain and are best placed to make decisions about what can realistically be achieved within the time frame of the sprint. They have a deep understanding of the technical aspects of the project and are well-equipped to evaluate the feasibility and effort required to complete each item in the backlog.

The Product Owner is responsible for setting the overall direction and priorities for the project. They work with stakeholders to determine the features and requirements that are most important to the success of the product. However, it is up to the Scrum Development Team to determine how best to implement those requirements, and what items to include in the Sprint Backlog.

By giving the Scrum Development Team the final say over what goes into the Sprint Backlog, Scrum ensures that the team is empowered to take ownership of the work they are responsible for and can work together to deliver the best possible product increment within the given sprint. This promotes collaboration and communication within the team and helps to ensure that the team is fully invested in the success of the project.

[.ka]
ka:null

'''

