---
layout: default 
title: "174 - Who starts the Daily Scrum Scrum Master "
---


[.question]
== Number 174-63effe689ebbe935e4c16b21

****

[.query]
The developers are new to Scrum and they've asked you, the experienced Scrum Master, who should start and lead the Daily Scrum. How do you respond?

[.list]
* [ ] A. Explain that the most senior developer on the team should start and lead the Scrum
* [ ] B. Explain that the most senior developer on the team leads the Scrum while the most junior developer speaks first
* [ ] B. Explain that the team lead will leads the Scrum while the senior developer speaks first
* [*] D. Explain how the developers can choose whatever structure they want for the Daily Scrum, so who starts it is up to them.
* [*] E. Explain that Scrum is hierarchy-less and it doesn't ask any individual to 'lead'.
****

[.answer]
DE

[.explanation]
It is up to the developers to decide how to run their Daily Scrum, which includes decisions about who starts it and who leads it.

"The Developers can select whatever structure and techniques they want, as long as their Daily Scrum focuses on progress toward the Sprint Goal and produces an actionable plan for the next day of work. This creates focus and improves self-management."

Furthermore, there are no 'team leads' or 'junior developers' in the eyes of Scrum. 

According to the Scrum Guide: "Within a Scrum Team, there are no sub-teams or hierarchies. It is a cohesive unit of professionals focused on one objective at a time, the Product Goal."

[.ka]
ka:Facilitation

'''

