---
layout: default 
title: "234 - Which two things are appropriate for a S"
---


[.question]
== Number 234-63effac69ebbe935e4c16aa2

****

[.query]
What should a Scrum Master do if the Development Team is missing the necessary skills, tools and infrastructure needed to complete the highest priority backlog items?

[.list]
* [*] A. Coach the Development Team on how to spend time during the sprint learning and improving their skills and acquiring tools they will need to complete important backlog items.
* [ ] B. Dissolve the Sprint and inform management that the Development Team is not ready to use the Scrum framework.
* [ ] C. Refocus the current Sprint on improving the Development Team's skills and acquiring the necessary infrastructure instead of delivering an increment.
* [ ] D. Instruct the Product Owner to accept partially Done Increments for this Sprint.
* [*] E. Establish a Definition of Done for backlog items that is achievable given the current infrastructure and skillsets.
****

[.answer]
AE

[.explanation]
The Scrum Developers are expected to have all of the skills required to complete all the Product Backlog items. If those skills do not exist, the developers must acquire them as they work on other Product Backlog items.

One way to continue to complete Backlog Items while infrastructure or tools are lacking might be to adjust the Definition of Done for certain backlog items so that Sprint Goals can be achieved.

Every Sprint must provide a real, tangible increment of work. There are no 'infrastructure sprints' in Scrum or 'Sprint Zeros.' Every Sprint must have the delivery of an increment of work as its goal.

[.ka]
ka:Coaching and Mentoring

'''

