---
layout: default 
title: "243 - When should a Sprint Goal be created Scr"
---


[.question]
== Number 243-63effc989ebbe935e4c16ae6

****

[.query]
When can the Sprint Goal be changed or adjusted?

[.list]
* [ ] A. The Sprint Goal can be changed or adjusted any time the Product Goal is changed or adjusted.
* [ ] B. The Sprint Goal can be changed or adjusted any time during the Daily Scrum.
* [ ] C. A Sprint Goal can be changed or adjusted any time during the Sprint.
* [*] D. The Sprint Goal must be finalized before the end of Sprint Planning and it cannot be changed throughout the Sprint.
* [ ] E. The Sprint Goal must be finalized before the Sprint starts and it cannot be changed throughout the Sprint.
****

[.answer]
D

[.explanation]
The Sprint Goal must be finalized before the end of Sprint Planning and it cannot be changed throughout the Sprint.

According to the Scrum Guide, "the whole Scrum Team then collaborates to define a Sprint Goal that communicates why the Sprint is valuable to stakeholders. The Sprint Goal must be finalized prior to the end of Sprint Planning."****

[.ka]
ka:Artifacts

'''

