---
layout: default 
title: "244 - When is implementation of a Product Back"
---


[.question]
== Number 244-63efface9ebbe935e4c16aa3

****

[.query]
When is a Product Backlog Item (PBI) considered fully complete and ready for release?

[.list]
* [*] A. A Product Backlog Item is complete when it is associated with a single, completed Increment of Work that meets the Definition of Done, making the PBI ready for release
* [ ] B. A Product Backlog Item is complete when further Increments of Work on it are no longer possible, making it ready for release.
* [ ] C. A Product Backlog Item is complete when a Quality Assurance team verifies that the work passes all acceptance criteria, making it ready for release
* [ ] D. A Product Backlog Item is complete when all work in the Sprint Backlog related to the item is finished, making it ready for release
****

[.answer]
A

[.explanation]
A Product Backlog Item is complete when all of its features are completed and it is not possible to create any further increments of work on it.

A Product Backlog Item is not necessarily associated with a single Increment of Work. A PBI may last for multiple Sprints, with each Sprint producing an Increment of Work that meets a Definition of Done for a given facet of a Product Backlog Item. That's why PBIs are decomposed by the development team - to break it up into manageable pieces of work.****

[.ka]
ka:forecasting

'''

