---
layout: default 
title: "817 - Which two things are appropriate for a Scrum Master"
---


[#question]
== 817-63effac69ebbe935e4c16aa2.

****

[#query]
--
What should a Scrum Master do if the Development Team is missing the necessary skills, tools and infrastructure needed to complete the highest priority backlog items?
--

[#list]
--
* [*] A. Coach the Development Team on how to spend time during the Sprint learning and improving their skills and acquiring tools they will need to complete important backlog items.
* [ ] B. Dissolve the Sprint and inform management that the Development Team is not ready to use the Scrum framework.
* [ ] C. Refocus the current Sprint on improving the Development Team's skills and acquiring the necessary infrastructure instead of delivering an increment.
* [ ] D. Instruct the Product Owner to accept partially Done Increments for this Sprint.

--
****

[#answer]
A

[#explanation]
--
The Scrum Developers are expected to have all of the skills required to complete all the Product Backlog items. If those skills do not exist, the developers must acquire them as they work on other Product Backlog items.

Every Sprint must provide a real, tangible increment of work. There are no 'infrastructure sprints' in Scrum or 'Sprint Zeros.' Every Sprint must have the delivery of an increment of work as its goal.
--

[#ka]
Coaching and Mentoring

'''

