:pdf-theme: some-theme.yml

== Stakeholders and Customers Quiz

One of the 13 tested categories on the Scrum Master exam is 'Stakeholders and Customers.'

The following questions will give you an idea of the scope and difficulty of these exam questions.

==== Question 1

****

Who on the Scrum Team is primarily responsible for engaging with stakeholders and C-suite executives?


* [ ] The Business Analyst.
* [ ] The Development Team.
* [ ] The Scrum Master.
* [ ] The Project Manager.
* [ ] The Product Owner.

****


'''

==== Question 2

****

What are the two primary responsibilities of a new Product Owner when taking ownership of a product that is currently under development with a long history of multiple, successful Sprints?

* [ ] Ensuring that the development teams know which Product Backlog Items provide the greatest value and should be developed first
* [ ] Describing product features in Use Case and story form.
* [ ] Providing detailed development specs to the development team.
* [ ] Interacting with stakeholders to learn how to represent their needs in the Product Backlog.
* [ ] Creating both functional and non-functional tests to validate the Increment meets the definition of Done.

****

'''

==== Question 3

****

A Product Owner can also be a stakeholder.

* [ ] True
* [ ] False

****


=== NEW

'''
==== Question 4

****

What guidance should the Scrum Master give to a developer wanting to talk to stakeholders?

* [ ] Only the Product Owner can talk to stakeholders
* [ ] Developers should only talk to stakeholders during the Sprint Review
* [ ] Developers should not talk to stakeholders
* [ ] Developers can talk to stakeholders whenever they like


****


'''

==== Question 5

****
Management and stakeholders are not happy with the effectiveness of the Scrum Team.

Who should management speak with first about this issue? Who is responsible for the effectiveness of the Scrum Team?


* [ ] The Scrum Master and the Product Owner
* [ ] The Product Owner
* [ ] The Scrum Master
* [ ] The Scrum developers
* [ ] The Scrum Team as a whole, inlcuding developers, the Product Owner and the Scrum Master


****


'''


<<<

=== Stakeholders and Customers Quiz Answers

==== Question 1

****

Who on the Scrum Team is primarily responsible for engaging with stakeholders and C-suite executives?


* [ ] The Business Analyst.
* [ ] The Development Team.
* [ ] The Scrum Master.
* [ ] The Project Manager.
* [ ] The Product Owner.

****

Option E is correct.

In the Scrum framework, the Product Owner is primarily responsible for engaging with stakeholders and C-suite executives. The Product Owner represents the stakeholders and is responsible for maximizing the value of the product or service that the Development Team is building. This involves managing the Product Backlog, which is a prioritized list of the work that the Development Team will complete during the upcoming Sprints.

As part of their role, the Product Owner engages with stakeholders and C-suite executives to understand their needs, gather feedback, and communicate the progress and status of the product development effort. This includes working with stakeholders to define the product vision, goals, and requirements, as well as gathering and prioritizing feedback on the product throughout the development process.

The Product Owner also works closely with the Development Team to ensure that the work being done is aligned with stakeholder needs and priorities. They provide guidance on the direction of the product and make decisions on behalf of the stakeholders regarding the prioritization of work in the Product Backlog.

While the Scrum Master and the Development Team may also interact with stakeholders and C-suite executives from time to time, it is the Product Owner who is primarily responsible for these activities. They are the ones who have the most direct contact with stakeholders and are the key point of communication between the Development Team and the outside world.


'''

==== Question 2

****

What are the two primary responsibilities of a new Product Owner when taking ownership of a product that is currently under development with a long history of multiple, successful Sprints?

* [ ] Ensuring that the development teams know which Product Backlog Items provide the greatest value and should be developed first
* [ ] Describing product features in Use Case and story form.
* [ ] Providing detailed development specs to the development team.
* [ ] Interacting with stakeholders to learn how to represent their needs in the Product Backlog.
* [ ] Creating both functional and non-functional tests to validate the Increment meets the definition of Done.

****

The Product Owner must prioritize the Product Backlog so that developers know which items provide the most value. If possible, the Product Owner will negotiate with the team to ensure these items get developed first.

Also, according to the Scrum Guide, "The Product Owner may represent the needs of many stakeholders in the Product Backlog." So interacting with and collaborating with stakeholders is important.

'''

==== Question 3

****

A Product Owner can also be a stakeholder.

* [ ] True
* [ ] False

****

There is no rule in Scrum that says a Product Owner can't also be a stakeholder.

Developers, the Scrum Master and the Product Owner could all potentially be customers or stakeholders in the product being built.

=== NEW

'''
==== Question 4

****

What guidance should the Scrum Master give to a developer wanting to talk to stakeholders?

* [ ] Only the Product Owner can talk to stakeholders
* [ ] Developers should only talk to stakeholders during the Sprint Review
* [ ] Developers should not talk to stakeholders
* [ ] Developers can talk to stakeholders whenever they like


****

There's no rule in Scrum that says a developer can't talk to a stakeholder.

Talking to stakeholders and mapping their wants into the Product Backlog is the responsibility of the Product Owner, but that doesn't mean nobody else can talk to stakeholders.

If your organization has rules that forbid developers or the Scrum Master from talking to stakeholders, then that's up to your organization. 

As far as the Scrum Guide goes, developers talking to stakeholders is fair dinkum.

'''

==== Question 5

****
Management and stakeholders are not happy with the effectiveness of the Scrum Team.

Who should management speak with first about this issue? Who is responsible for the effectiveness of the Scrum Team?


* [ ] The Scrum Master and the Product Owner
* [ ] The Product Owner
* [ ] The Scrum Master
* [ ] The Scrum developers
* [ ] The Scrum Team as a whole, inlcuding developers, the Product Owner and the Scrum Master


****

Option C is correct.

The Scrum Master is the one responsible for the effectiveness of the Scrum Team.

'''



