:pdf-theme: some-theme.yml

== Self-Managed Teams Quiz

One of the 13 tested categories on the Scrum Master exam is 'Self-Managed Teams.'

The following questions will give you an idea of the scope and difficulty of these exam questions.



==== Question 1
--
A cross functional team:
(Select 2 answers.)
--


--
* [ ] Will have the skills to work on multiple layers in the software stack
* [ ] Are skilled enough to develop components that require a diverse skillset
* [ ] Will only work on specialized components that require a specific set of skills
* [ ] Will specialize in one, specific layer in the software stack
* [ ] Will write code and build applications, and then pass testing off to a specialized team.

--

==== Question 2
--
The goal of every Scrum Team is to produce usable and valuable Increments as quickly as possible.

What is the best way to organize the members of a Scrum Team to make them most productive?
(Select 1 answers.)
--


--
* [ ] A. Have a strong Team Lead delegate work to team members based on their skills and abilities.
* [ ] B. Have the Scrum Team be self-organize and collectively accountable for their productivity
* [ ] C. Create sub-teams that specialize on a specific layer of the tech stack.
* [ ] D. Have individuals specialize on the components with which they are most familiar.

--

==== Question 3
--
Who is responsible for reporting status updates from the Daily Scrum back to stakeholders?
(Select 1 answers.)
--


--
* [ ] A. The Product Owner.
* [ ] B. The Scrum Master.
* [ ] C. The team lead.
* [ ] D. None of the above.

--

==== Question 4
--
Who selects the items in the Product Backlog to be included in the current Sprint?
(Select 1 answers.)
--


--
* [ ] The Product Owner
* [ ] The Scrum Master
* [ ] The Developers
* [ ] The Scrum Team as a whole
* [ ] The Stakeholders

--

==== Question 5
--
Who on the Scrum Team can fire a developer?
(Select 1 answers.)
--


--
* [ ] The Product Owner
* [ ] The Scrum Master
* [ ] The Development Team
* [ ] Nobody

--

<<<

=== Answers

==== Answer 1
****

[#query]
--
A cross functional team:
--

[#list]
--
* [*] Will have the skills to work on multiple layers in the software stack
* [*] Are skilled enough to develop components that require a diverse skillset
* [ ] Will only work on specialized components that require a specific set of skills
* [ ] Will specialize in one, specific layer in the software stack
* [ ] Will write code and build applications, and then pass testing off to a specialized team.

--
****

[#answer]

The correct answers are A and B.

[#explanation]
--
A cross functional team will build a variety of different components that will operate on various layers in the software stack.

"Scrum Teams are cross-functional, meaning the members have all the skills necessary to create value each Sprint." -The Scrum Guide, page 5
--



==== Answer 2
****

[#query]
--
The goal of every Scrum Team is to produce usable and valuable Increments as quickly as possible.

What is the best way to organize the members of a Scrum Team to make them most productive?
--

[#list]
--
* [ ] A. Have a strong Team Lead delegate work to team members based on their skills and abilities.
* [*] B. Have the Scrum Team be self-organize and collectively accountable for their productivity
* [ ] C. Create sub-teams that specialize on a specific layer of the tech stack.
* [ ] D. Have individuals specialize on the components with which they are most familiar.

--
****

[#answer]

The correct answer is B.

[#explanation]
--
The Scrum Team should work together, as a whole, to create a product that provides full end-to-end functionality within the requirements of the Product Backlog and the Definition of Done.

There are no sub-teams in Scrum, nor are their leaders or managers. 

"Within a Scrum Team, there are no sub-teams or hierarchies. They are also self-managing, meaning they internally decide who does what, when, and how."
--



==== Answer 3
****

[#query]
--
Who is responsible for reporting status updates from the Daily Scrum back to stakeholders?
--

[#list]
--
* [ ] A. The Product Owner.
* [ ] B. The Scrum Master.
* [ ] C. The team lead.
* [*] D. None of the above.

--
****

[#answer]

The correct answer is D.

[#explanation]
--
The Daily Scrum is not a status update and nowhere in the Scrum Guide does it suggest that what happens in the Daily Scrum should be reported to stakeholders.

It is a time for developers to adapt to changes and make changes to the Sprint Backlog if it is necessary to keep the Sprint Goal in focus.


--



==== Answer 4
****

[#query]
--
Who selects the items in the Product Backlog to be included in the current Sprint?
--

[#list]
--
* [ ] The Product Owner
* [ ] The Scrum Master
* [*] The Developers
* [ ] The Scrum Team as a whole
* [ ] The Stakeholders

--
****

[#answer]

The correct answer is C.

[#explanation]
--
It is the Developers who select the Product Backlog items to be included in the current Sprint. This is done with input from the Product Owner, but the Developers have the final say."Through discussion with the Product Owner, the Developers select items from the Product Backlog to include in the current Sprint." -The Scrum Guide, page 8
--



==== Answer 5
****

[#query]
--
Who on the Scrum Team can fire a developer?
--

[#list]
--
* [ ] The Product Owner
* [ ] The Scrum Master
* [ ] The Development Team
* [*] Nobody

--
****

[#answer]

The correct answer is D.

[#explanation]
--
Scrum does not grant any of its members to fire another member.

A development team can choose have a developer removed from the team. But this is not the same as firing a developer.

If a development team chooses to remove a member, that is the right they have as a self-organizing team. Whether a company fires that developer, or allocates them to a different team, is not a concern of the Scrum team.
--


