---
layout: default 
title: "906 - The Development Team should have all the"
---


[#question]
== 906-63effafb9ebbe935e4c16aa8.

****

[#query]
--
What are the skills and capabilities the Scrum Development Team should have in order to ensure effective performance throughout the Sprint?
--

[#list]
--
* [*] A. The ability to decompose Product Backlog items (PBIs) and progressively create Increments of Work until a functional release is possible.
* [ ] B. The ability to perform all of the core software development work, with the exception of any specialized testing that would require additional tools and staging environments.
* [ ] C. The ability to complete a development project within budget and within the timeline agreed upon with the Product Owner.
* [ ] D. The ability to take direction from the Scrum Master and complete Product Backlog items assigned to them by the Product Owner.

--
****

[#answer]
A

[#explanation]
--
The Scrum Development team must be able to decompose a PBI and create as many Increments of Work that are necessary to complete the PBI and make the item ready for release.

A Product Backlog Item (PBI) is a high-level user story or requirement that represents a feature, function, or other unit of work that needs to be delivered in order to meet the product's goals. Decomposing a PBI means breaking it down into smaller, more manageable pieces of work that can be completed by the Scrum development team during a sprint.

The process of decomposing a PBI involves analyzing it in more detail, identifying the sub-tasks, dependencies, and other factors involved, and then creating smaller PBIs that can be individually prioritized, estimated, and worked on by the team. This allows the team to better understand the requirements of the PBI and the work involved, which in turn helps with planning and delivering the work effectively.

Decomposition is an ongoing process throughout the Scrum framework. As the team progresses through the sprint, they may discover additional details or dependencies that require further decomposition of PBIs, or they may need to adjust their plan based on feedback from stakeholders or changes in the product's requirements. By continually decomposing PBIs, the team can ensure they have a clear understanding of the work involved and can prioritize, estimate, and deliver the product backlog items more effectively.
--

[#ka]
Forecasting and Release Planning

'''

