
[.question]
==== Number 63efffab9ebbe935e4c16b45

****

[.query]
According to the Scrum framework, when does a Sprint officially come to an end?

[.list]
* [*] A. When the predetermined length, or 'time box,' for the Sprint expires.
* [ ] B. When all Product Backlog items are complete.
* [ ] C. When all Product Backlog items selected for the Sprint are complete.
* [ ] D. When a full increment that delivers value to the client is complete.
****

[.answer]
A

[.explanation]
A Sprint expires when it's predetermined length for the Sprint expires.

A Sprint may be two weeks, three weeks or four weeks. That's up to the team to decide.

One the time allotted for the Sprint is met, the Sprint ends and a new Sprint begins.

Even if Product Backlog items are not finished, or even if the team failed to deliver any value, the Sprint is not extended. When the allotted time-box is met, the Sprint ends.

It's worth nothing that the Scrum Guide does not mention a time-box for a Sprint. It mentions a time-box for Sprint Planning, the Sprint Review and the Sprint Retrospective, but it does not actually use the word 'time-box' when referring to a Sprint.****

[.ka]
ka:Events

'''

