
[.question]
==== Number 63effb739ebbe935e4c16ab7

****

[.query]
What are the two primary responsibilities of a new Product Owner when taking ownership of a product that is currently under development with a long history of multiple, successful Sprints?

[.list]
* [*] A. Ensuring that the development teams know which Product Backlog Items provide the greatest value and should be developed first
* [ ] B. Describing product features in Use Case and story form.
* [ ] C. Providing detailed development specs to the development team.
* [*] D. Interacting with stakeholders to learn how to represent their needs in the Product Backlog.
* [ ] E. Creating both functional and non-functional tests to validate the Increment meets the definition of Done.
****

[.answer]
AD

[.explanation]
The Product Owner must prioritize the Product Backlog so that developers know which items provide the most value. If possible, the Product Owner will negotiate with the team to ensure these items get developed first.

Also, according to the Scrum Guide, "The Product Owner may represent the needs of many stakeholders in the Product Backlog." So interacting with and collaborating with stakeholders is important.****

[.ka]
ka:Stakeholders

'''

