
[.question]
==== Number 63effa4c9ebbe935e4c16a94

****

[.query]
You, the Scrum Master, have been told that the quality assurance (QA) tests performed by an external team have been delayed, and due to this delay, it's unlikely the Definition of Done will be achieved before the end of this 3-week Sprint. However, if the Sprint was extended a week, the QA work would likely be done. 

How would you proceed as a Scrum Master? (Choose 2)

[.list]
* [ ] A. Extend the Sprint a week to allow QA to complete their work.
* [*] B. Investigate why the Scrum Team does not have all the cross-functional skills to achieve the Definition of Done without an external QA team
* [ ] C. Remove QA work from the Definition of Done for this Sprint.
* [ ] D. Explain to the organization that Scrum is not designed to manage the work performed by people external to the Scrum Team.
* [ ] E. Turn the next Sprint into a 'Performance and Security' sprint and focus on these two non-functional aspects of the code.
****

[.answer]
B

[.explanation]
A Scrum Team must have all of the skills necessary to complete the Definition of Done. The Scrum Team cannot outsource work that is part of their Definition of Done and still have that work managed through Scrum.

Extending the Sprint is never an option. The Sprint length is fixed when the Sprint starts.

The Definition of Done can always be discussed and updated. However, the Scrum Master does not have the right to unilaterally change the Definition of Done, and changes to the Definition of Done are best discussed in the Sprint Retrospective.

Furthermore, the Definition of Done should not be changed midway through a Sprint to accommodate moving goalposts. Doing so would be antithetical to Scrum.****

[.ka]
ka:self-managing teams

'''

