---
layout: default 
title: "811 - When it is appropriate to update the Spr"
---


[#question]
== 811-63efff599ebbe935e4c16b3c.

****

[#query]
--
As the Scrum Master it is clear to you that the Sprint Goal is not going to be reached if the Sprint Backlog isn't adjusted, and new items aren't added. In Scrum, who has the right to add items to the Sprint Backlog?
--

[#list]
--
* [ ] A. The Product Owner, as they are responsible for prioritizing the Product Backlog
* [*] B. The Development Team, as they own the Sprint Backlog.
* [ ] C. The Scrum Master if the change needs to be made to keep the Sprint Goal in focus
* [ ] D. Both the Scrum Master and members of the Development Team can add or remove items from the Sprint Backlog.

--
****

[#answer]
B

[#explanation]
--
The development team has full control over the Sprint Backlog during a Sprint. Only the development team has the authority to add or remove items from the Sprint backlog.

Anyone can discuss the Sprint Backlog to the development team and relay any concerns with them, but it is the development team that has the final say.
--

[#ka]
Artifacts

'''

