---
layout: default 
title: "124 - Which of the following services are appr"
---


[#question]
== 124-63effd179ebbe935e4c16af8.

****

[#query]
--
What responsibilities does the Scrum Master have with regards to the Daily Scrum?
--

[#list]
--
* [*] A. Encourage the developers to select whatever techniques and structure they want during the Daily Scrum.
* [ ] B. Ensure everyone on the development team has a chance to speak and have their voice heard.
* [ ] C. Ask each member if there are any impediments that need to be addressed.
* [ ] D. Take notes and act as a scribe so the developers don't have to.
* [*] E. The Scrum Master must coach the team so they know that the Daily Scrum does not exceed the 15 minute time-box

--
****

[#answer]
AE

[#explanation]
--
The Scrum Master does not actively participate in the Daily Scrum. The Scrum Master does not ask questions, take notes for the team or instruct any individual to speak.

With regards to the Daily Scrum, the Scrum Master's responsibility is to make sure it is used properly within the context of Scrum, which means coaching around it being self-managed, self-organized and time-boxed to 15 minutes.

From the Scrum Guide: "The Daily Scrum is a 15-minute event for the Developers of the Scrum Team. The Developers can select whatever structure and techniques they want, as long as their Daily Scrum focuses on progress toward the Sprint Goal and produces an actionable plan for the next day of work."
--

[#ka]
Coaching and Mentoring

'''

