---
layout: default 
title: "823 - What are the two primary ways a Scrum Ma"
---


[#question]
== 823-63effcda9ebbe935e4c16af1.

****

[#query]
--
How can a Scrum Master help a Development Team maintain their highest levels of productivity?
--

[#list]
--
* [*] A. By removing impediments the Development Team has identified as impeding their progress
* [ ] B. By ensuring all developers arrive to the Daily Scrum on time
* [ ] D. By prioritizing the highest value features in the Product Backlog.
* [*] C. By coaching Development Teams on ways to achieve consensus-based decisions.

--
****

[#answer]
AD

[#explanation]
--
A Scrum Master can help a Development Team to maintain their highest levels of productivity by continuously removing impediments and enabling the team to work in an environment of self-organization. 

Additionally, the Scrum Master can provide guidance, coaching, and support to ensure the Development Team is taking the most effective approach to their work.
--

[#ka]
Coaching and Mentoring

'''

