---
layout: default 
title: "135 - Why does the Product Owner want the Deve"
---


[#question]
== 135-63effc439ebbe935e4c16ad8.

****

[#query]
--
What is the best way for the Product Owner to ensure that the Scrum developers transparently deliver high-quality, releasable increments of work that meet the needs of the stakeholders?
--

[#list]
--
* [ ] A. Have the team lead personally perform all code merges into the master branch.
* [*] B. Have the software development team strictly adhere to the organization's Definition of Done (DoD).
* [ ] C. Reprimand the team when product quality falls below an agreed upon quality gate.
* [ ] D. Have the developers send all work through a QA team before release.

--
****

[#answer]
B

[#explanation]
--
The Product Owner needs the Development Team to adhere to the definition of "Done" because it helps ensure that the team delivers high-quality, releasable increments of work that meet the needs of the stakeholders.

The definition of "Done" is a shared understanding between the Product Owner and the Development Team about what it means for a product backlog item to be considered complete. It includes a set of criteria that must be met for each item, such as passing tests, meeting performance standards, and conforming to coding standards.

By adhering to the definition of "Done," the Development Team ensures that they are producing work that is of high quality, that meets the expectations of the Product Owner, and that is releasable. This, in turn, helps the Product Owner manage stakeholder expectations, as they can rely on the Development Team to consistently deliver work that meets the agreed-upon criteria.

Moreover, adhering to the definition of "Done" promotes transparency and accountability. The Development Team commits to delivering work that meets the agreed-upon criteria, which helps to ensure that they take ownership of the quality of their work. The Product Owner can also track progress more accurately, as they can trust that items that meet the definition of "Done" are truly complete and can be included in the product release.

In short, adherence to the definition of "Done" helps ensure that the Development Team produces high-quality work that meets the needs of the stakeholders and contributes to the overall success of the product.
--

[#ka]
Done

'''

