---
layout: default 
title: "832 - Which three purposes does the definition"
---


[#question]
== 832-63effb469ebbe935e4c16ab1.

****

[#query]
--
What are the three primary objectives served by the Definition of Done (DoD)?
--

[#list]
--
* [*] A. The DoD guides the Development Team on the number of Product Backlog items the should select for the Sprint Backlog.
* [*] B. The DoD creates a common understanding across the team with regards to when development work is completed.
* [ ] C. The DoD describes the purpose, reasoning, and time allotment for each Scrum event.
* [ ] D. The DoD describes the work that must be done before the Sprint is ended.
* [*] E. The DoD helps to increase transparency throughout the Scrum framework.

--
****

[#answer]
ABE

[#explanation]
--
Scrum's "Definition of Done" is a shared understanding among the Scrum Team of what it means for a product backlog item to be considered complete. It is an agreed-upon set of criteria that a product backlog item (PBI), or a decomposition of a PBI, must meet before it can be considered "complete."

By establishing a clear "Definition of Done," Scrum increases transparency by providing a shared understanding of what constitutes a completed product backlog item. This shared understanding helps ensure that everyone involved in the development process has the same expectations of what is expected in the final product.

The "Definition of Done" also helps developers estimate how much work to add to the Sprint Backlog. Because the team has a clear understanding of what constitutes a completed product backlog item, they can more accurately estimate how much work needs to be done to achieve that level of completeness. This can help the team better plan their work for the sprint and avoid overcommitting to work they may not be able to complete.

Finally, the "Definition of Done" helps developers understand when work is complete. By providing a clear definition of what it means for a product backlog item to be considered complete, the team can avoid confusion or misunderstandings about what is expected from them. This clarity can help prevent issues such as unfinished work being carried over to future sprints or incomplete work being considered "done," leading to potential issues in the final product.

Overall, the "Definition of Done" is a valuable tool in promoting transparency, accurate estimation, and clarity around when work is considered complete in Scrum.
--

[#ka]
Done

'''

