---
layout: default 
title: "149 - Which statement best describes Scrum Scr"
---


[#question]
== 149-63effe8f9ebbe935e4c16b25.

****

[#query]
--
What of the following is the most accurate description of Scrum as defined by the Scrum Guide?
--

[#list]
--
* [ ] A. A complete, incremental and iterative software development process 
* [ ] B. An incomplete, incremental and iterative software development process 
* [*] C. A purposefully incomplete, lightweight framework to help find solutions for complex problems
* [ ] D. A purposefully complete, lightweight framework to help find solutions for complex problems

--
****

[#answer]
C

[#explanation]
--
Scrum is not just for the domain of software development, so any definitions that try to pin Scrum to the software development world are incorrect.

Scrum self-describes as being a purposefully incomplete, lightweight framework designed to help find solutions for complex problems.

From the Scrum Guide: "Scrum is a lightweight framework that helps people, teams and organizations generate value through adaptive solutions for complex problems. The Scrum framework is purposefully incomplete, only defining the parts required to implement Scrum theory."
--

[#ka]
Empiricism

'''

