---
layout: default 
title: "852 - Which three of the following are timebox"
id: 852-63effa599ebbe935e4c16a95.
---


[#question]
== 852-63effa599ebbe935e4c16a95.

****

[#query]
--
Which of the following Scrum events are time-boxed to limit the amount of time spent on them?
--

[#list]
--
* [ ] A. Standup Meetings.
* [ ] B. The Release Sprint.
* [*] C. The Sprint Retrospective.
* [*] D. Sprint Planning. 
* [ ] E. Stakeholder Meetings.
* [ ] F. Sprint Zero.
* [*] G. The Daily Scrum.

--
****

[#answer]
CDG

[#explanation]
--
The Sprint Retrospective is a time-boxed event that occurs at the end of each Sprint and allows the team to reflect on their processes and identify areas for improvement. 

Sprint Planning is also time-boxed and occurs at the beginning of each Sprint, allowing the team to plan and prioritize their work for the upcoming Sprint. 

The Daily Scrum is another time-boxed event that occurs daily during the Sprint and allows the team to synchronize their work and plan for the day.

Options A, B, E, and F are not correct because they are not Scrum events. They may be performed by some Scrum Teams, but they are not discussed at all in the Scrum Guide.
--

[#ka]
Events

'''

