---
layout: default 
title: "894 - A Scrum Master is introducing Scrum to a"
---


[#question]
== 894-63effc249ebbe935e4c16ad3.

****

[#query]
--
Corporate stakeholders are very busy, as multiple projects are going online this quarter.

The stakeholders have asked to attend every-other Sprint Review to minimize the number of meetings on their calendars. How do you as a Scrum Master respond?
--

[#list]
--
* [*] A. Coach the stakeholders and the team on how to make the meetings more productive and positive
* [ ] B. Agree with the request of the stakeholders, as reducing meetings is in line with Agile principles
* [*] C. Educate stakeholders on the importance of Sprint Reviews and work to facilitate more engaging Sprint Reviews.
* [ ] D. Consult privately with the Product Owner and see if they will agree to fewer meetings

--
****

[#answer]
AC

[#explanation]
--
The Scrum Master should use the opportunity to explain the importance of a Sprint Review and the value the team receives from the stakeholders participation in the Sprint Review.

--

[#ka]
Facilitation

'''

