---
layout: default 
title: "203 - Who determines how work is performed dur"
---


[#question]
== 203-63effa8c9ebbe935e4c16a9b.

****

[#query]
--
Who has final say over how work will be scheduled and performed during a Sprint?
--

[#list]
--
* [ ] A. The Stakeholders.
* [ ] B. The Project Manager.
* [ ] C. The Product Owner.
* [ ] D. The Scrum Master.
* [*] E. The Development Team.

--
****

[#answer]
E

[#explanation]
--
In Scrum, the development team is responsible for planning and executing the work during a Sprint. The Scrum framework is designed to be a collaborative process where the development team works closely with the Product Owner to ensure that the work being done is aligned with the project's goals and priorities.

The development team is the only group of people who have a say over how work will be scheduled during a Sprint because they are the ones who are actually doing the work. They are the ones who are responsible for estimating the effort required to complete each item in the Sprint backlog and for deciding how to organize the work within the Sprint.

This allows the development team to take ownership of the work and to have the autonomy to decide how to best organize their work in a way that allows them to be as efficient and effective as possible. This also ensures that the development team is able to focus on the work that they have committed to completing during the Sprint, without being distracted by external pressures or competing priorities.

--

[#ka]
Forecasting and Release Planning

'''

