---
layout: default 
title: "213 - The Product Owner must release each Incr"
---


[#question]
== 213-63efff349ebbe935e4c16b38.

****

[#query]
--
Why might the Product Owner refuse to immediately release an increment into production?
--

[#list]
--
* [ ] A. Increments are automatically released into production so it is not possible to refuse the release
* [ ] B. The Product Owner needs confirmation from the developers that they have completed the Sprint to release an increment
* [*] C. The time of the release does not make sense for customers or stakeholders
* [ ] D. The Product Owner cannot refuse to release an increment into production

--
****

[#answer]
C

[#explanation]
--
If the timing of the release of an increment is not in the best interest of users or stakeholders, the Product Owner does not need to release it immediately.

In the context of agile software development, the Product Owner is responsible for defining and prioritizing the features of the product being developed. An "increment" refers to a small, functional improvement or enhancement made to the product during the development process.

The Product Owner should be responsible for deciding when each incremental change or improvement to the product is ready to be released to users or customers. This decision should be based on various factors, such as the overall impact of the increment on the product's functionality, the level of quality and stability of the increment, and the potential benefits and risks of releasing the increment at a particular time.

The idea is that by releasing small increments of the product regularly, the development team can receive quick feedback from users or customers, which can be used to inform further development and improvements. This approach can also help to reduce the risk of large, complex changes failing or causing problems when released all at once.
--

[#ka]
Forecasting and Release Planning

'''

