---
layout: default 
title: "938 - How much work must a Development Team do"
---


[#question]
== 938-63effa1d9ebbe935e4c16a8e.

****

[#query]
--
What is the extent of work a Development Team needs to perform on a Product Backlog item selected for a Sprint for it to be considered ready to be part of an Increment?
--

[#list]
--
* [ ] A. As much work as the team can complete in the current Sprint, after which it becomes part of the Increment.
* [ ] B. An equal amount of time on analysis, engineering, QA, programming, testing, and documentation.
* [ ] D. The Development Team works on a Product Backlog Item until the Scrum Master says it meets the Definition of Done
* [*] D. The Development Team works on a Product Backlog Item until it meets the agreed upon Definition of Done.

--
****

[#answer]
D

[#explanation]
--
The Development Team is expected to work on the selected Product Backlog items during a Sprint. The amount of work they do on an item is not predefined, but it is up to the Development Team to decide based on the time and resources available in the Sprint. The Development Team works in a time-boxed environment, and it tries to achieve the Sprint Goal by completing the Product Backlog items. Hence, the Development Team should do as much work as possible on the selected Product Backlog item within the Sprint. If any work is remaining, it will be added to the Product Backlog and prioritized in future Sprints.

Working hard and pushing undone work into a future sprint highlights the principle of the Development Team to do as much work as possible within the Sprint's time-box. The Development Team needs to identify the amount of work they can fit into a Sprint, and they should complete the work within that period. If there is any incomplete work, it can be added to the Product Backlog for prioritization in a future Sprint. 

--

[#ka]
Product Value

'''

