---
layout: default 
title: "930 - Which two activities will a Product Owne"
---


[#question]
== 930-63effcf29ebbe935e4c16af4.

****

[#query]
--
According to the Scrum Guide, which two of the following statements is true about the Product Owner?
--

[#list]
--
* [*] A. The Product Owner may delegate the creation of Product Backlog Items to an associate.
* [ ] B. The Product Owner may be a committee or collection of individuals who collaboratively perform the role.
* [*] C. The organization must fully respect and trust the independent decisions of the Product Owner.
* [ ] D. The Product Owner should coach the developers in self-management and cross-functionality.
* [ ] E. The Product Owner must attend and participate in the Daily Scrum.

--
****

[#answer]
AC

[#explanation]
--
According to the Scrum Guide, the Product Owner may delegate work to others. However, the Product Owner must be one person who is fully trusted by the organization. The Product Owner job cannot be done by a committee.

From the Scrum Guide:

"The Product Owner ... may delegate the responsibility to others. Regardless, the Product Owner remains accountable. For Product Owners to succeed, the entire organization must respect their decisions. These decisions are visible in the content and ordering of the Product Backlog, and through the inspectable Increment at the Sprint Review. The Product Owner is one person, not a committee."

--

[#ka]
Product Backlog Management

'''

