---
layout: default 
title: "948 - What done means Choose two Scrum Master "
---


[#question]
== 948-63effe3b9ebbe935e4c16b1b.

****

[#query]
--
The Scrum Guide describes Scrum as:
--

[#list]
--
* [*] A. An iterative framework
* [ ] B. A waterfall based process
* [*] C. An incremental framework
* [ ] D. An Agile framework
* [ ] E. A software development process

--
****

[#answer]
AC

[#explanation]
--
The Scrum Guide describes Scrum as both an iterative and incremental framework.

The combination of incremental and iterative development in Scrum allows the team to deliver a product that is both usable and valuable to the customer, while also allowing for changes and adjustments to be made as necessary. The incremental aspect ensures that the product is developed in small, manageable pieces that can be tested and released to the customer, while the iterative aspect ensures that the team is continuously learning and adapting to feedback in order to improve the product and the development process.
--

[#ka]
Product Value

'''

