---
layout: default 
title: "234 - How should Product Backlog items be chos"
---


[#question]
== 234-63effea19ebbe935e4c16b27.

****

[#query]
--
Two Scrum Teams working on the same Product want to do Sprint Planning together so they can coordinate the items they pull from the common Product Backlog. 

What would you as a Scrum Master advise this team?
--

[#list]
--
* [ ] A. Two teams working on the same project should have separate Product Backlogs, making this unnecessary.
* [ ] B. Two separate Scrum Teams should not be openly discussing their development work with each other
* [ ] C. The Product Owner should be selecting Product Backlog Items for each team, so the joint meeting is unnecessary
* [ ] D. Explain to the teams that Scrum forbids shared planning meetings.
* [*] E. Encourage the teams to be self-managed, introduce new processes like the one they suggested, and have them introspect during the Sprint Retrospective and adapt accordingly.

--
****

[#answer]
E

[#explanation]
--
Scrum is self-described as an incomplete framework. That means there is a great deal of flexibility and creatively allowed within the bounds of what constitutes Scrum.

Generally speaking, if Scrum doesn't explicitly forbid it, then teams are free to explore it. Shared Sprint Planning meetings might be a great process for the team to implement.
--

[#ka]
Product Backlog Management

'''

