---
layout: default 
title: "986 - Choose two responsibilities of a selforg"
---


[#question]
== 986-63effad89ebbe935e4c16aa4.

****

[#query]
--
What are two of the responsibilities of a self-organized and self-managed Scrum development Team?
--

[#list]
--
* [ ] A. A self-organized Scrum development team will reorder the Product Backlog.
* [*] B. A self-organized Scrum development team will choose Product Backlog items to work on during the Sprint.
* [*] C. A self-organized Scrum development team will perform the work planned in the Sprint Backlog.
* [ ] D. A self-organized Scrum development team will  always try to increase velocity.
* [ ] E. A self-organized Scrum development team will report daily progress to stakeholders to ensure the Scrum pillar of transparency and value of openness.

--
****

[#answer]
BC

[#explanation]
--
A Scrum development team will choose which backlog items will be included in the Sprint backlog, and they will then work on completing as much of the planned work as possible.

Scrum developers choose product backlog items for the Sprint because the product backlog represents the prioritized list of features, functionalities, and improvements that need to be developed for the product. The product backlog is managed by the Product Owner, who is responsible for ensuring that the items in the backlog are prioritized based on the value they will provide to the end-users or stakeholders.

During Sprint Planning, which is one of the Scrum events, the development team works with the Product Owner to select the items that they will work on during the upcoming Sprint. The team considers the highest priority items in the product backlog and assesses whether they are feasible to complete during the Sprint. They take into account factors such as their capacity, the complexity of the items, and any dependencies that may exist between the items.

The development team's goal is to select a set of product backlog items that they can complete within the Sprint, while delivering value to the stakeholders. By selecting items that are high priority and achievable within the Sprint, the team can help ensure that the product is continuously improved and that the stakeholders receive value from the development effort.
--

[#ka]
Self-managing teams

'''

